In [ ]:
# Data visualization
# BTech Computer Science Stream, January 2025
# Week 3 Python Language Basics
# Name: Oswin Vion Dsilva, 240905268,Section CE, Date: 30/01/2024

In [5]:
# Imports
import numpy as np

In [6]:
# Question 1
# Generate a 3x4 NumPy array with random integers between 1and 50.
# a. Calculate and print the Mean, Median, and Standard Deviation of the array
# b. Print the Sum of all elements and the sum of each row.
# c. Reshape the 3x4 array into a 2x6 array and print it.

# Generation of the array
var_arrA = np.random.randint(1,51,size = (3,4))
print("Original Array:")
print(var_arrA)
print(f"Dimension of the array is : {var_arrA.shape}\n")


# Part a. Mean, Median, and Standard deviation
print(f"Mean = {np.mean(var_arrA)}")
print(f"Median = {np.median(var_arrA)}")
print(f"Standard Deviation = {np.std(var_arrA)}\n")


# Part b. Sum of elements
print(f"Sum of all elements = {np.sum(var_arrA)}")
for i in range(var_arrA.shape[0]):
    print(f"Sum of row {i+1}:{np.sum(var_arrA[i])}")


# Part c. Reshaping the array
var_arrA = var_arrA.reshape(2,6)
print("\nArray after reshaping :")
print(var_arrA)

Original Array:
[[47  5 17 13]
 [36 28 19 11]
 [10 20 44 33]]
Dimension of the array is : (3, 4)

Mean = 23.583333333333332
Median = 19.5
Standard Deviation = 13.244233546046456

Sum of all elements = 283
Sum of row 1:82
Sum of row 2:94
Sum of row 3:107

Array after reshaping :
[[47  5 17 13 36 28]
 [19 11 10 20 44 33]]


In [7]:
# Question 2
# 2. Create two (3 * 3) matrices using NumPy and print it. 
# Perform and print the results of the following linear algebra operations
# a. Matrix addition
# b. Matrix subtraction
# c. Matrix multiplication (element-wise and dot product)
# d. Transpose of a matrix
# e. Determinant and inverse (if applicable)


# Generation of array 
var_arrB = np.random.randint(50,size = (3,3))
var_arrC = np.random.randint(50,size = (3,3))
print("Array 1:")
print(var_arrB)
print("\nArray 2:")
print(var_arrC)

# Part a. Matrix Addition
print(f"\nSum of the two arrays is \n{var_arrB + var_arrC}")

# Part b. Matrix Subtraction
print(f"\nDifference of the two arrays is \n{var_arrB - var_arrC}")

# Part c. Matrix Multiplication
print(f"\nElementwise multiplication of the two arrays is \n{var_arrB * var_arrC}")
print(f"\nMultiplication of the two arrays is \n{var_arrB @ var_arrC}")


# Part d. Matrix Tranpose
print(f"\nTranpose of the first array is \n{var_arrB.T}")
print(f"\nTranpose of the second array is \n{var_arrC.T}")

# Part e. Determinant and inverse
print(f"\nDeterminant of first array is {np.linalg.det(var_arrB)}")
if(np.linalg.det(var_arrB)!=0):
    print(f"\nInverse of first array is \n{np.linalg.inv(var_arrB)}")
print(f"\nDeterminant of second array is {np.linalg.det(var_arrC)}")
if(np.linalg.det(var_arrC)!=0):
    print(f"\nInverse of second array is \n{np.linalg.inv(var_arrC)}")


Array 1:
[[28 16  8]
 [12 14 25]
 [33 30  6]]

Array 2:
[[25 15 39]
 [40 39  8]
 [47  3 35]]

Sum of the two arrays is 
[[53 31 47]
 [52 53 33]
 [80 33 41]]

Difference of the two arrays is 
[[  3   1 -31]
 [-28 -25  17]
 [-14  27 -29]]

Elementwise multiplication of the two arrays is 
[[ 700  240  312]
 [ 480  546  200]
 [1551   90  210]]

Multiplication of the two arrays is 
[[1716 1068 1500]
 [2035  801 1455]
 [2307 1683 1737]]

Tranpose of the first array is 
[[28 12 33]
 [16 14 30]
 [ 8 25  6]]

Tranpose of the second array is 
[[25 40 47]
 [15 39  3]
 [39  8 35]]

Determinant of first array is -7416.000000000007

Inverse of first array is 
[[ 0.08980583 -0.01941748 -0.03883495]
 [-0.10153722  0.01294498  0.08144552]
 [ 0.01375405  0.0420712  -0.02696872]]

Determinant of second array is -48642.000000000015

Inverse of second array is 
[[-0.02756877  0.00838781  0.02880227]
 [ 0.02105177  0.01969491 -0.02795938]
 [ 0.03521648 -0.01295177 -0.00770939]]
